version: '3'

set: [pipefail]

#docs:
#  streaming_replication: https://hevodata.com/learn/postgresql-streaming-replication/#master1

includes:
  cfg: "replication.vars.task.yml"
  sql:
    taskfile: ../common/sql.task.yml
    vars:
      CFG_FILE: "replication.vars.task.yml"
    internal: true

tasks:
  default:
    cmds:
      - task --list-all

  full_run:
    cmds:
      - task: restart_postgres
      - task: create_replication_user

  restart_postgres:
    deps:
      - kill
    vars:
      CURR_DIR:
        sh: pwd
    cmds:
      - task: rebuild_volume
      - |
        docker run -ti \
          --network {{.NETWORK_NAME}} \
          --name {{.MAIN_CONTAINER}} \
          -e POSTGRES_PASSWORD={{.PG_PASS}} \
          -v "{{.CURR_DIR}}/main.postgresql.conf":/etc/postgresql/postgresql.conf \
          -v "{{.CURR_DIR}}/pg_hba.conf":/var/lib/postgresql/data/pg_hba.conf \
          {{.POSTGRES_IMAGE}} \
          -c 'config_file=/etc/postgresql/postgresql.conf'
      - sleep 3

  rebuild_volume:
    cmds:
      - docker volume rm pg-cluster-vol
      - docker volume create --name pg-cluster-vol


  create_replication_user:
    cmds:
      - task: sql:execute_on_db
        vars:
          SERVER: "{{.MAIN_CONTAINER}}"
          SQL_QUERY: "CREATE USER replication_user REPLICATION LOGIN ENCRYPTED PASSWORD 'repl';"
    ignore_error: true

  kill:
    cmds:
      - docker kill {{.MAIN_CONTAINER}} || true
      - docker rm {{.MAIN_CONTAINER}} || true
    internal: true