version: '3'

set: [pipefail]

includes:
  cfg: common/vars.task.yml

  sql:
    taskfile: common/sql.task.yml
    vars:
      CFG_FILE: "common/vars.task.yml"

  debezium: debezium.task.yml

  utils: common/utils.task.yml

  #replication: replication/Taskfile.yml

tasks:
  default:
    cmds:
      - task --list-all

  full_debezium_run:
    cmds:
      # - task: sql:create_test_db
      - task: debezium:restart_debezium
      - task: sql:create_test_table

